### ISSUE TITLE
Why need wait_interval?

### ISSUE THREAD

**Issue by IdemenB** [Dansvidania/camunda-worker#13]
Hi all, last year I implemented a Python library for orchestrating Camunda external tasks through its REST API, just like the one here you guys started. It was never used for production though.

What I remember is that there are two very important timing configuration while performing fetch&task operations:

1) asyncresponsetimeout -> this is the lenght of long polling. So, if set for 60 secs, the very same connection between the Camunda server and the client (rust code here) is kept-alive for 60 secs. If an external task with the same topic name as the worker is created during that time, it is immediately pulled to the worker.  Once 60 sec expires the connection is automatically built again and the timer is reset.
2) lock duration -> Once an external task is fetched by the client (rust code), it should be locked because the complete (or errror if the worker fails to complete the job) operation should be done by the same worker only. This parameter configures the duration for which an external task will be kept locked for the worker which fetched it in the first place.

In the lib I see you set a wait duration and wait for that time to re-initiate fetch and lock function. Why do you see that necessary?

**Comment by dan-amoroso** [comment]
hi @IdemenB , could you point me to the documentation from Camunda regarding asyncresponsetimeout? 

As a quick answer to your question, this library was started a bit _impromptu_ for us to be able to play around with Camunda and Rust, and the choice to use wait_interval is due to it being the simplest way to handle the task pulling with my _limited_ knowledge of camunda at the time.

While the idea for the future is to allow exponential backoffs and other strategies to determine the waiting interval, I am also open to implement other solutions that better interface with the Camunda API. If you can help in that direction I would greatly appreciate it.

**Comment by IdemenB** [comment]
Thank yuu for the answer @Dansvidania. In this particular topic, it is really easy, one just needs to define the aforementioned two parameters while sending the fetch and lock request. They should be set in line with the expected duration of the external tasks in question. If one task is expected to be completed in 10 secs, for example, Camunda should reserve that task for that worker at least for 10 secs, so lock duration parameter should be a bit longer than that. When it comes to the duration of long polling ("asyncResponseTimeout") the doc says it is allowed up to 30 min. I'm not sure whether it's a good thing to make it that long or now. I'll make my tests for a 60 sec long polling.

**Comment by IdemenB** [comment]
I'm sorry I missed you asked about the documentation:

Please see the information in the "asyncResponseTimeout" field here: https://docs.camunda.org/manual/latest/reference/rest/external-task/fetch/

And here is a related and valuable forum topic:

https://forum.camunda.org/t/setting-the-timing-parameters-for-external-task-clients/8621

**Comment by dan-amoroso** [comment]
It really does seem like it would just be simpler to use that and do away with any form of backoff, at least as an MVP for the library. Thank you for the docs and forum topic. I am wondering how did I miss it :)

I will try to implement the change and prepare a PR

**Comment by IdemenB** [comment]
This could depend on the use case though. As far as I understand, what long polling does is transferring the need to make a query of new created external tasks from the client to the Camunda engine. In other words, for the duration you are polling, you are not making a query but the engine does (constantly). What you gain is the elimination of HTTP requests' IO. But still somewhere a constant querying occurs.

If the business need does not require an "instant" handling of the created external task, you can set some intervals like you did with wait_interval and query every 1,5,10.. minutes as you need and don't create a constant effort of querying the database.

Please take a look at the following post about this detail.

https://forum.camunda.org/t/external-tasks-long-polling-where-is-the-resources-actually-being-saved/11496

**Comment by dan-amoroso** [comment]
I see that to some degree using long-polling might not scale, and my plan for the library is to offer a choice between different pulling strategies, for example as an enum to be provided as an argument to `worker::run_topic_handler`.

I do think I should offer a basic/simplest approach to get people started quickly and easy and it seems like long polling might be the best option for that.
